version: '3.8'

services:
  backend:
    image: node:20.11.1 # Official Node.js 20.11.1 image
    container_name: backend
    working_dir: /usr/src/app # Set the working directory inside the container
    volumes:
      - /var/www/clockhead/portfolio:/usr/src/app # Mount the actual repo directory into the container
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/portfolio
      - RESEND_API_KEY=re_E8hvGP3Y_E4vCnj4xEfuR3qLyJW4fJbLd
      - NODE_ENV=production
      - FRONTEND_URL=https://clockhead.dev
      # SESSION_SECRET
      # JWT_SECRET
    depends_on:
      - mongo
    command: pm2 start app.js --name backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
